In [2]:
from libs.wrapper_coinbase.coinbase import CoinbaseAPI
from dotenv import load_dotenv
from dataclasses import dataclass
import os

load_dotenv('./auth/cb.env')

@dataclass
class API:
    api_key: str
    api_secret: str

creds = API(
    os.environ.get('api_key'),
    os.environ.get('api_secret')
)

cli = CoinbaseAPI(api_key= creds.api_key, api_secret= creds.api_secret)

df = cli.transactions_inpandas()
df.head()

,order_id,product_id,side,date,time,commission,sequence_timestamp,size,price
0,bd5771fe-a120-498f-9692-b9f521c6aa7a,USDT-GBP,BUY,2023-01-17,14:37:58.848424,1.236717e-07,2023-01-17T14:37:58.848424Z,490.0,0.8138
1,bd5771fe-a120-498f-9692-b9f521c6aa7a,USDT-GBP,BUY,2023-01-17,14:37:58.816866,1.155270e-02,2023-01-17T14:37:58.816866Z,490.0,0.8138
4,02fd0c99-3c34-4657-8187-a17daad13043,USDT-GBP,BUY,2023-01-12,20:06:58.856732,1.165241e-07,2023-01-12T20:06:58.856732Z,490.0,0.8185
5,02fd0c99-3c34-4657-8187-a17daad13043,USDT-GBP,BUY,2023-01-12,20:06:58.830324,5.087469e-03,2023-01-12T20:06:58.830324Z,490.0,0.8185
6,ec84bb8d-dc76-445b-b099-ac2c58ccec37,USDT-GBP,BUY,2023-01-12,11:15:03.165528,1.301543e-07,2023-01-12T11:15:03.165528Z,490.0,0.8215